import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cfg=window.ACADEMY_CONFIG||{};
const supabase=cfg.supabaseUrl&&cfg.supabaseAnonKey?createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let currentUser=null,memberAccess=null,currentRoles=[],adminData={paths:[],modules:[],lessons:[]},remotePaths=[];
const paths = [
  {glyph:'✧',title:'El camino de las velas',tag:'VELAS · VELomancia'.toUpperCase(),level:'Iniciación',lessons:6,color:'linear-gradient(135deg,#654660,#bd8c79)',desc:'Descubre el lenguaje simbólico de la llama y crea rituales con intención.'},
  {glyph:'☾',title:'Tarot: el primer umbral',tag:'TAROT · ORÁCULOS',level:'Iniciación',lessons:8,color:'linear-gradient(135deg,#414060,#a88bad)',desc:'Conoce los arcanos y aprende a escuchar las historias que cuentan.'},
  {glyph:'☼',title:'Rituales de luna',tag:'RITUAL · CICLOS',level:'Iniciación',lessons:5,color:'linear-gradient(135deg,#9d7651,#dec091)',desc:'Acompaña tus intenciones con los ciclos y ceremonias de la luna.'},
  {glyph:'♧',title:'Quiromancia: leer la mano',tag:'QUIROMANCIA · LECTURA',level:'Iniciación',lessons:7,color:'linear-gradient(135deg,#49655c,#9bb3a0)',desc:'Explora líneas, montes y formas como un mapa de símbolos personales.'},
  {glyph:'☽',title:'Sueños y mundos sutiles',tag:'SUEÑOS · EXPLORACIÓN',level:'Intermedio',lessons:9,color:'linear-gradient(135deg,#3d465d,#8c9cb2)',desc:'Cultiva el recuerdo onírico, la visualización y los sueños lúcidos.'},
  {glyph:'✺',title:'Astrología para tu práctica',tag:'ASTROLOGÍA · COSMOS',level:'Intermedio',lessons:10,color:'linear-gradient(135deg,#58436c,#aa86ab)',desc:'Lleva los símbolos del cielo a tu propio mapa de aprendizaje.'},
  {glyph:'∞',title:'El arte de la meditación',tag:'MEDITACIÓN · PRESENCIA',level:'Iniciación',lessons:6,color:'linear-gradient(135deg,#687060,#b9b18c)',desc:'Prácticas para aquietar el ruido y escuchar tu mundo interior.'},
  {glyph:'◉',title:'Registros del alma',tag:'AKÁSHICOS · INTUICIÓN',level:'Avanzado',lessons:8,color:'linear-gradient(135deg,#685044,#c29174)',desc:'Un recorrido de introspección guiada a través de preguntas y símbolos.'}
];
const seedEntries = [
  {title:'La llama que bailaba',type:'RITUAL',date:'21 SEP 2026',body:'Encendí una vela blanca pensando en claridad. La llama se inclinaba y volvía a levantarse. Me recordó que puedo moverme sin perder mi centro.',tags:['Velas','Claridad'],private:true},
  {title:'Un jardín bajo el agua',type:'SUEÑO',date:'18 SEP 2026',body:'Soñé con caminar por un jardín sumergido. Las flores seguían vivas, aunque todo alrededor estaba en silencio.',tags:['Sueños','Agua'],private:true},
  {title:'La carta de La Estrella',type:'LECTURA',date:'15 SEP 2026',body:'Pregunté qué energía me acompaña en este comienzo. La imagen me invitó a confiar en los pasos pequeños.',tags:['Tarot','Inicio'],private:true}
];
const feedItems = [
  {initial:'M',name:'Mariana Sol',rank:'Aprendiz de tarot',time:'hace 12 min',title:'Mi primera lectura de tres cartas ✨',body:'Hoy hice una tirada para mí misma sin buscar una respuesta perfecta. Me sorprendió lo mucho que tenía para decirme cuando simplemente dejé que las imágenes hablaran.',likes:24,replies:8,colors:'a1'},
  {initial:'S',name:'Sofía Luna',rank:'Practicante de velas',time:'hace 1 h',title:'¿Qué música acompaña sus rituales?',body:'Estoy armando una playlist para mi pequeño altar. Busco sonidos suaves, un poco de naturaleza y algo que me ayude a entrar en ese espacio íntimo. ¿Qué escuchan ustedes?',likes:17,replies:12,colors:'a2'},
  {initial:'A',name:'Ana del Río',rank:'Buscadora',time:'hace 3 h',title:'Hoy me regalé diez minutos para mí',body:'Sin cartas, sin ritual elaborado. Solo respiré, escribí una intención y la guardé en mi grimorio. A veces el primer paso también merece celebrarse.',likes:31,replies:5,colors:'a3'}
];
const readStore=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let entries=readStore('adb_entries',seedEntries), posts=readStore('adb_posts',[]), activeFilter='all';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function save(){localStorage.setItem('adb_entries',JSON.stringify(entries));localStorage.setItem('adb_posts',JSON.stringify(posts))}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2700)}
function showView(view){if(view==='admin'&&!currentRoles.includes('admin')){toast('El panel está reservado para la cuenta administradora.');return}$$('.view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));const labels={inicio:'UMBRAL',academia:'ACADEMIA',grimorio:'GRIMORIO',aquelarre:'AQUELARRE',camino:'MI CAMINO',admin:'ADMINISTRACIÓN'};$('#crumbCurrent').textContent=labels[view]||'UMBRAL';$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(view==='admin')loadAdminContent()}
function renderPaths(){const displayPaths=[...paths,...remotePaths];$('#pathGrid').innerHTML=displayPaths.map((p,i)=>`<article class="path-card" data-path="${i}"><div class="path-art" style="background:${p.color}"><span class="path-glyph">${p.glyph}</span><span class="path-stars">✦　 ·　✧　　 ·　　　 ✦　　·</span></div><div class="path-card-body"><div class="card-eyebrow">${escapeHtml(p.tag)}</div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.desc)}</p><div class="path-card-foot"><span>${escapeHtml(p.level)} · ${p.lessons||'Ver'} lecciones</span><b>Explorar →</b></div></div></article>`).join('');$$('.path-card').forEach(card=>card.addEventListener('click',()=>openPath(displayPaths[Number(card.dataset.path)])))}
function renderEntries(){const q=($('#entrySearch')?.value||'').toLowerCase();const filtered=entries.filter(e=>(activeFilter==='all'||e.type.toLowerCase().includes(activeFilter))&&`${e.title} ${e.body} ${e.tags.join(' ')}`.toLowerCase().includes(q));$('#entryGrid').innerHTML=filtered.length?filtered.map(e=>`<article class="entry-card"><div class="entry-top"><span class="entry-type">${escapeHtml(e.type)}</span><span class="entry-date">${escapeHtml(e.date)}</span></div><h3>${escapeHtml(e.title)}</h3><p>${escapeHtml(e.body)}</p><div class="entry-tags">${e.tags.map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><span class="private">♙ ${e.private?'Privado':'Compartido'}</span></article>`).join(''):`<div class="empty-state"><span>✧</span><b>Esta página aún espera ser escrita.</b><small>Guarda aquí una práctica, un sueño o un símbolo que quieras recordar.</small></div>`;$('#entryCount').textContent=entries.length}
function renderFeed(){const all=[...posts.map(p=>({...p,user:'Tú',rank:'Aprendiz',initial:'L',time:'ahora'})),...feedItems];$('#feedList').innerHTML=all.map((p,i)=>`<article class="post-card"><div class="post-author"><span class="avatar ${p.colors||''}">${escapeHtml(p.initial)}</span><span><b>${escapeHtml(p.user||p.name)}</b><small>${escapeHtml(p.rank)}</small></span><span class="post-time">${escapeHtml(p.time)}</span></div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.body)}</p><div class="post-actions"><button class="like-button" data-like="${i}">♡ ${p.likes??0} Me inspira</button><button>◯ ${p.replies??0} respuestas</button><button>↗ Compartir</button></div></article>`).join('');$$('.like-button').forEach(b=>b.addEventListener('click',()=>{b.classList.toggle('liked');b.textContent=b.classList.contains('liked')?'♥ Me inspira':'♡ '+(Number(b.textContent.match(/\d+/)?.[0]||0))+' Me inspira'}))}
const backdrop=$('#modalBackdrop');
function openModal({eyebrow='TU GRIMORIO',title='Abre una nueva página',content}){$('#modalEyebrow').textContent=eyebrow;$('#modalTitle').textContent=title;$('#modalContent').innerHTML=content;backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');setTimeout(()=>backdrop.querySelector('input,textarea,button')?.focus(),50)}
function closeModal(){backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true')}
function openEntry(){openModal({eyebrow:'TU GRIMORIO · SOLO TÚ',title:'Guarda este momento.',content:`<form id="entryForm"><label class="field-label">Título de tu página</label><input class="modal-input" name="title" required maxlength="80" placeholder="¿Qué quieres recordar?"/><label class="field-label">Tipo de entrada</label><select class="modal-select" name="type"><option>Ritual</option><option>Lectura</option><option>Sueño</option><option>Intuición</option><option>Reflexión</option></select><label class="field-label">Lo que viviste o descubriste</label><textarea class="modal-textarea" name="body" required maxlength="1500" placeholder="No hay una forma correcta de escribirlo..."></textarea><label class="field-label">Etiquetas, separadas por coma</label><input class="modal-input" name="tags" placeholder="Intuición, luna, inicio"/><button class="primary-button modal-submit">Guardar en mi grimorio <span>✦</span></button><p class="modal-note">Esta página será privada. Puedes compartirla después desde tu grimorio.</p></form>`});$('#entryForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);entries.unshift({title:d.get('title'),type:String(d.get('type')).toUpperCase(),date:new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()).toUpperCase(),body:d.get('body'),tags:String(d.get('tags')).split(',').map(x=>x.trim()).filter(Boolean).slice(0,4),private:true});save();renderEntries();closeModal();toast('Tu página quedó guardada en el grimorio ✦')})}
async function hasAccess(){if(!supabase)return true;if(!currentUser)return false;const{data,error}=await supabase.rpc('has_academy_access');if(error){console.error('No se pudo consultar el acceso',error.message);return false}memberAccess=Boolean(data);return memberAccess}
function openPath(path){(async()=>{if(supabase&&!currentUser){openAuth();return}if(!(await hasAccess())){openPaywall();return}openModal({eyebrow:`${path.tag} · ${path.level.toUpperCase()}`,title:path.title,content:`<p class="modal-note" style="font-size:11px;line-height:1.8;text-align:left">${escapeHtml(path.desc)} Este camino reúne ${path.lessons} lecciones breves, prácticas guiadas y páginas para registrar lo que descubras en tu grimorio.</p><div class="path-modal-list"><div>✦ <span>Fundamentos y vocabulario de la práctica</span></div><div>✧ <span>Ejercicios guiados para comenzar</span></div><div>☽ <span>Una práctica para llevar a tu vida cotidiana</span></div></div><button class="primary-button modal-submit" id="enrollPath">Comenzar mi camino <span>↗</span></button><p class="modal-note">Tu progreso y tus páginas del grimorio se guardan en tu cuenta.</p>`});$('#enrollPath').addEventListener('click',()=>{closeModal();toast('Tu inscripción quedará guardada en tu cuenta ✦')})})()}
function openPaywall(){openModal({eyebrow:'TU PRÓXIMO DESPERTAR',title:'Cruza el umbral.',content:`<p class="modal-note" style="font-size:11px;line-height:1.8;text-align:left">La membresía abre los caminos, ceremonias, círculos de aprendices y herramientas de la Academia. Tus páginas personales del grimorio siguen siendo tuyas.</p><div class="membership-box"><span>✦</span><div><b>Miembro de la Academia</b><small>Caminos completos · Nuevas prácticas · Círculos</small></div></div><button class="primary-button modal-submit" id="hotmartCheckout">Continuar a Hotmart <span>↗</span></button><p class="modal-note">El acceso se activa automáticamente cuando Hotmart confirma tu compra.</p>`});$('#hotmartCheckout').addEventListener('click',()=>{if(cfg.hotmartCheckoutUrl){window.location.assign(cfg.hotmartCheckoutUrl)}else toast('Configura la URL de checkout de Hotmart en config.js.')})}
function openAuth(){openModal({eyebrow:'ENTRA EN TU ESPACIO',title:'Vuelve a tu camino.',content:`<form id="authForm"><label class="field-label">Tu correo electrónico</label><input class="modal-input" name="email" type="email" required autocomplete="email" placeholder="tu@correo.com"/><button class="primary-button modal-submit">Enviarme un enlace de acceso <span>↗</span></button><p class="modal-note">Te enviaremos un enlace seguro para iniciar sesión o crear tu cuenta con este correo.</p></form>`});$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');if(!supabase){toast('La autenticación se activa al configurar Supabase.');return}const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});if(error){toast('No se pudo enviar el enlace: '+error.message);return}$('#modalContent').innerHTML='<p class="modal-note" style="font-size:12px">Revisa tu correo. Te enviamos un enlace para entrar a la Academia. ✦</p>'})}
function createPost(){openModal({eyebrow:'EL AQUELARRE TE ESCUCHA',title:'Comparte tu experiencia.',content:`<form id="postForm"><label class="field-label">Título</label><input class="modal-input" name="title" required maxlength="100" placeholder="¿Qué te gustaría compartir?"/><label class="field-label">Tu publicación</label><textarea class="modal-textarea" name="body" required maxlength="1200" placeholder="Comparte una práctica, una pregunta o un pequeño descubrimiento..."></textarea><button class="primary-button modal-submit">Publicar en el aquelarre <span>✦</span></button><p class="modal-note">Al publicar, tu nombre de perfil será visible para este círculo.</p></form>`});$('#postForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);posts.unshift({title:d.get('title'),body:d.get('body')});save();renderFeed();closeModal();toast('Tu voz ya está en el aquelarre ✦')})}
function openPractice(){openModal({eyebrow:'PRÁCTICA DE HOY · 5 MIN',title:'Escucha lo que la llama revela.',content:`<div class="practice-steps"><p><b>01 · Prepara tu espacio</b><br>Busca un lugar tranquilo. Puedes usar una vela apagada o simplemente imaginar una llama; no necesitas encender nada.</p><p><b>02 · Vuelve a tu intención</b><br>Respira despacio tres veces. Recuerda algo que estés comenzando a nutrir.</p><p><b>03 · Observa sin buscar respuestas</b><br>Imagina el movimiento de la luz. ¿Qué palabra, color o sensación aparece primero?</p><label class="field-label">¿Qué te llevas de esta práctica?</label><textarea class="modal-textarea" id="practiceNote" placeholder="Escribe una palabra o una reflexión..."></textarea><button class="primary-button modal-submit" id="savePractice">Guardar en mi grimorio <span>✦</span></button></div>`});$('#savePractice').addEventListener('click',()=>{const body=$('#practiceNote').value.trim();if(body){entries.unshift({title:'La práctica de la llama',type:'RITUAL',date:new Intl.DateTimeFormat('es-CO',{day:'2-digit',month:'short',year:'numeric'}).format(new Date()).toUpperCase(),body,tags:['Práctica diaria','Velas'],private:true});save();renderEntries()}closeModal();toast('Práctica completada. Tu camino deja una huella ✦')})}
function bind(){ $$('[data-view]').forEach(el=>el.addEventListener('click',()=>showView(el.dataset.view)));$('#adminShortcut').addEventListener('click',()=>showView('admin'));$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#modalClose').addEventListener('click',closeModal);backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('#newEntry').addEventListener('click',openEntry);$('#createPost').addEventListener('click',createPost);$('#startPractice').addEventListener('click',openPractice);$('#continueCourse').addEventListener('click',()=>openPath(paths[0]));$('#upgradeButton').addEventListener('click',openPaywall);$('#authButton').addEventListener('click',()=>currentUser?signOut():openAuth());$('#entrySearch').addEventListener('input',renderEntries);$$('.filter-pill').forEach(b=>b.addEventListener('click',()=>{$$('.filter-pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderEntries()}));$('#searchButton').addEventListener('click',()=>{showView('academia');toast('Explora los caminos de aprendizaje')});$('#eventButton').addEventListener('click',()=>toast('El calendario de ceremonias estará disponible pronto ✦'));$('#editProfile').addEventListener('click',()=>toast('La edición de perfil estará disponible al crear tu cuenta.'));$('#creatorInfo').addEventListener('click',()=>openModal({eyebrow:'EL CAMINO DE LA MAESTRA',title:'Tu sabiduría también puede florecer.',content:`<p class="modal-note" style="font-size:11px;line-height:1.8;text-align:left">Al completar una senda podrás solicitar un perfil de practicante. Desde allí podrás publicar lecturas, abrir círculos, ofrecer talleres y recibir reservas dentro de la Academia.</p><div class="path-modal-list"><div>✧ <span>Perfil profesional y catálogo de servicios</span></div><div>☽ <span>Agenda y reservas de tus consultantes</span></div><div>✦ <span>Herramientas para crear talleres y círculos</span></div></div><button class="primary-button modal-submit" id="creatorWait">Entendido <span>✦</span></button>`}));document.addEventListener('click',e=>{if(e.target.id==='creatorWait')closeModal();if(e.target.classList.contains('join-button')){e.target.textContent='✓';e.target.style.color='#76578b';toast('Círculo añadido a tus espacios ✦')}})}
async function signOut(){if(supabase)await supabase.auth.signOut();currentUser=null;memberAccess=null;updateAccount();toast('Has cerrado sesión.')}
function updateAccount(){const button=$('#authButton');if(!button)return;button.textContent=currentUser?(currentUser.email?.split('@')[0]||'Mi cuenta'):'Entrar';button.title=currentUser?'Cerrar sesión':'Iniciar sesión';$$('.admin-nav').forEach(el=>el.classList.toggle('hidden',!currentRoles.includes('admin')));$('#adminShortcut').classList.toggle('hidden',!currentRoles.includes('admin'))}
async function loadRoles(){currentRoles=[];if(supabase&&currentUser){const{data,error}=await supabase.from('academy_roles').select('role').eq('user_id',currentUser.id);if(!error)currentRoles=(data||[]).map(row=>row.role);await loadPublishedPaths()}updateAccount()}
async function loadPublishedPaths(){if(!supabase||!currentUser)return;const{data,error}=await supabase.from('academy_paths').select('*').eq('status','published').order('position');if(error)return;remotePaths=(data||[]).map((x,i)=>({id:x.id,title:x.title,tag:x.discipline.toUpperCase(),level:x.level,lessons:adminData.modules.filter(m=>m.path_id===x.id).length||'Explorar',color:['linear-gradient(135deg,#654660,#bd8c79)','linear-gradient(135deg,#414060,#a88bad)','linear-gradient(135deg,#49655c,#9bb3a0)'][i%3],glyph:'✧',desc:x.description}));renderPaths()}
function slugify(value){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function setAdminSelect(select,rows,label){select.innerHTML=rows.length?rows.map(row=>`<option value="${row.id}">${escapeHtml(label(row))}</option>`).join(''):'<option value="">Primero crea el elemento anterior</option>'}
async function loadAdminContent(){if(!supabase||!currentUser||!currentRoles.includes('admin'))return;const [p,m,l]=await Promise.all([supabase.from('academy_paths').select('*').order('position'),supabase.from('academy_modules').select('*').order('position'),supabase.from('academy_lessons').select('*').order('position')]);if(p.error||m.error||l.error){$('#adminContentList').innerHTML='<div class="empty-state"><b>No se pudo cargar el contenido.</b><small>Confirma que aplicaste la migración nueva de administración en Supabase.</small></div>';return}adminData={paths:p.data||[],modules:m.data||[],lessons:l.data||[]};remotePaths=adminData.paths.filter(x=>x.status==='published').map((x,i)=>({id:x.id,title:x.title,tag:x.discipline.toUpperCase(),level:x.level,lessons:adminData.modules.filter(m=>m.path_id===x.id).length,color:['linear-gradient(135deg,#654660,#bd8c79)','linear-gradient(135deg,#414060,#a88bad)','linear-gradient(135deg,#49655c,#9bb3a0)'][i%3],glyph:'✧',desc:x.description}));renderPaths();setAdminSelect($('#adminModuleForm [name=path_id]'),adminData.paths,x=>x.title);setAdminSelect($('#adminLessonForm [name=module_id]'),adminData.modules,x=>`${adminData.paths.find(p=>p.id===x.path_id)?.title||'Camino'} · ${x.title}`);renderAdminRows()}
function renderAdminRows(){const groups=adminData.paths.map(p=>{const modules=adminData.modules.filter(m=>m.path_id===p.id);return `<article class="admin-path-row"><div class="admin-row-main"><span class="admin-path-glyph">✧</span><div><b>${escapeHtml(p.title)}</b><small>${escapeHtml(p.discipline)} · ${escapeHtml(p.level)} · ${escapeHtml(p.status)}</small></div><div class="admin-row-actions"><button data-edit="path" data-id="${p.id}">Editar</button><button data-delete="path" data-id="${p.id}">Eliminar</button></div></div>${modules.map(m=>`<div class="admin-child-row"><span>↳ ${escapeHtml(m.title)}</span><div><button data-edit="module" data-id="${m.id}">Editar</button><button data-delete="module" data-id="${m.id}">Eliminar</button></div>${adminData.lessons.filter(l=>l.module_id===m.id).map(l=>`<div class="admin-lesson-row"><span>· ${escapeHtml(l.title)}</span><div><button data-edit="lesson" data-id="${l.id}">Editar</button><button data-delete="lesson" data-id="${l.id}">Eliminar</button></div></div>`).join('')}</div>`).join('')}</article>`}).join('');$('#adminContentList').innerHTML=groups||'<div class="empty-state"><b>Aún no hay caminos creados.</b><small>Usa el formulario de arriba para crear el primero.</small></div>';$$('[data-edit]').forEach(b=>b.addEventListener('click',()=>editAdminItem(b.dataset.edit,b.dataset.id)));$$('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteAdminItem(b.dataset.delete,b.dataset.id)))}
function putHiddenId(form,id){let field=form.querySelector('[name=id]');if(!field){field=document.createElement('input');field.type='hidden';field.name='id';form.append(field)}field.value=id}
function editAdminItem(kind,id){const map={path:['adminPathForm',adminData.paths],module:['adminModuleForm',adminData.modules],lesson:['adminLessonForm',adminData.lessons]};const[formId,rows]=map[kind],record=rows.find(row=>row.id===id),form=$('#'+formId);if(!record)return;putHiddenId(form,id);Object.entries(record).forEach(([key,value])=>{const field=form.elements.namedItem(key);if(field&&field.type!=='hidden')field.value=value??''});form.querySelector('button[type=submit],button:not([type])').textContent='Guardar cambios';form.scrollIntoView({behavior:'smooth',block:'center'});toast('Edita los campos y guarda los cambios.')}
async function deleteAdminItem(kind,id){if(!confirm('¿Eliminar este contenido? Los elementos que dependan de él también se eliminarán.'))return;const table={path:'academy_paths',module:'academy_modules',lesson:'academy_lessons'}[kind];const{error}=await supabase.from(table).delete().eq('id',id);if(error){toast('No se pudo eliminar: '+error.message);return}toast('Contenido eliminado.');loadAdminContent()}
function resetAdminForm(form){form.reset();form.querySelector('[name=id]')?.remove();form.querySelector('button[type=submit],button:not([type])').textContent=form.id==='adminPathForm'?'Guardar camino':form.id==='adminModuleForm'?'Guardar módulo':'Guardar lección'}
function bindAdminForms(){const specs=[['adminPathForm','academy_paths',d=>({...(d.id?{id:d.id}:{}),title:d.title,slug:d.id?adminData.paths.find(p=>p.id===d.id)?.slug:`${slugify(d.title)}-${crypto.randomUUID().slice(0,5)}`,discipline:d.discipline.toUpperCase(),description:d.description,level:d.level,status:'published',position:adminData.paths.length,created_by:currentUser.id})],['adminModuleForm','academy_modules',d=>({...(d.id?{id:d.id}:{}),path_id:d.path_id,title:d.title,position:adminData.modules.filter(x=>x.path_id===d.path_id).length})],['adminLessonForm','academy_lessons',d=>({...(d.id?{id:d.id}:{}),module_id:d.module_id,title:d.title,body:d.body,position:adminData.lessons.filter(x=>x.module_id===d.module_id).length,status:'published'})]];specs.forEach(([formId,table,shape])=>$('#'+formId).addEventListener('submit',async e=>{e.preventDefault();if(!supabase||!currentRoles.includes('admin')){toast('El panel requiere una sesión administradora.');return}const raw=Object.fromEntries(new FormData(e.currentTarget).entries()),payload=shape(raw),{error}=await supabase.from(table).upsert(payload);if(error){toast('No se pudo guardar: '+error.message);return}toast('Guardado en la Academia ✦');resetAdminForm(e.currentTarget);await loadAdminContent()}))}
bind();bindAdminForms();renderPaths();renderEntries();renderFeed();updateAccount();
if(supabase){supabase.auth.getSession().then(async({data})=>{currentUser=data.session?.user||null;await loadRoles()});supabase.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;memberAccess=null;loadRoles();if(currentUser)toast(`Bienvenida a tu Academia ✦`)})}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
